theme: jekyll-theme-cayman
title: Verano Cientifico Virtual
description: 2020
defaults:
  - scope:
      path: "docs"
    values:
      image: true
{% assign image_files = site.static_files | where: "image", true %}
{% for myimage in image_files %}
  {{ myimage.path }}
{% endfor %}
